<?php

namespace AppBundle\Entity\Repository;

/**
 * RedacteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * Récupére l'utilisateur par email 
     * 
     * Récupérer un utilisateur par email indépendamment de la casse
     * @param type $email
     * @return type
     */
    public function getOneByEmailCI($email)
    {
        
        $qb = $this->createQueryBuilder('r');
        $qb->where($qb->expr()->eq('UPPER(r.email)', ':email'))
            ->setParameter('email', strtoupper($email));
        
        return $qb->getQuery()->getOneOrNullResult();
        
    }
}
